name: Deployment
on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # deploy to a heroku app specifically created for testing only
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uci-cubesat-websocket-server"
          heroku_email: "chillinthestar@outlook.com"
